### ISSUE TITLE
The installer crashes after asking me where to get the snapshot.

### ISSUE THREAD

**Issue by njmurarka** [osmosis-labs/osmosis-installer#46]
As per https://github.com/osmosis-labs/osmosis-installer, trying to install Osmosis mainnet full node (not a validator) via the installer and after I select the option to download the pruned snapshot, I get this:

```Please choose the location nearest to your node:
1) Netherlands
2) Singapore
3) SanFrancisco (WARNING: Location usually slow)
    
Traceback (most recent call last):
  File "i.py", line 1572, in <module>
  File "i.py", line 1570, in start
  File "i.py", line 1559, in restart
  File "i.py", line 1489, in selectNetwork
  File "i.py", line 1419, in initEnvironment
  File "i.py", line 1307, in initSetup
  File "i.py", line 1145, in installLocation
  File "i.py", line 1088, in initNodeName
  File "i.py", line 1016, in setupMainnet
  File "i.py", line 956, in customPortSelection
  File "i.py", line 907, in pruningSettings
  File "i.py", line 847, in dataSyncSelection
  File "i.py", line 815, in mainNetType
  File "i.py", line 751, in mainNetLocation
AttributeError: 'NoneType' object has no attribute 'lower'
```

This happened in response to choosing 1 from the following:

```Please choose from the following options:
1) Download a snapshot from ChainLayer (recommended)
2) Start at block 1 and automatically upgrade at upgrade heights (replay from genesis, can also select rocksdb here)
3) Exit now, I only wanted to install the daemon```

**Comment by matteyu** [comment]
Probably because of this: https://github.com/osmosis-labs/osmosis-installer/blob/main/osmosis-installer.py#L746

colorprint() is used for informational text only. It needs to be replaced with print() to read input. That's probably why the location is NoneType.

**Comment by matteyu** [comment]
Can verify this is happening.

It's this line: https://github.com/osmosis-labs/osmosis-installer/blob/main/osmosis-installer.py#L751

The first time it goes into the function, `args.snapshotLocation` is not assigned yet.  So you can't call `.lower()` on it.  Simply removing it from the check will resolve it.  The selection for `snapshotLocation` is already all in lowercase so don't need to lower it again during the check.

**Comment by njmurarka** [comment]
Thanks. That fix does get one step further, but I noticed that the snapshot probably did not download anyways (since the "download" finishes instantly), and afterwards, I found that the the osmosisd binary was crashing on start.

Has anyone tested this?

**Comment by ValarDragon** [comment]
Sorry about this, I broke this in #44 . I had only tested via interactive python method calls, and missed:
* None as an option
* Somehow something with globals broke. Still not sure how that happened.

Working on fixing this. (Then we should get some dockerized testing method, to easily guarantee this doesn't happen again)

**Comment by njmurarka** [comment]
No worries. Would really appreciate it if this could be sorted, for sure. I was able to run the installer a few weeks ago and it ran flawlessly, downloaded the snapshot, and ran the chain.

Tried to run this in every different environment possible without luck.

**Comment by ValarDragon** [comment]
What I have in that PR _should_ fix it. (waiting for snapshot download to complete to be 100% sure) You can run it in two steps rn
```
wget https://raw.githubusercontent.com/osmosis-labs/osmosis-installer/dev/fix_snapshot_installer/osmosis-installer.py
python3 osmosis-installer.py
```

**Comment by njmurarka** [comment]
```
ubuntu@ip-172-26-6-126:~$ python3 osmosis-installer.py
  File "osmosis-installer.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by ValarDragon** [comment]
Hrmm, that wget line is working on my machine. (No HTML headers getting onto my downloaded file)

**Comment by njmurarka** [comment]
My fault. I had an older copy of the script I had downloaded and manually try to doctor. 

So the new one had a (1) suffix.

I tried again, more intelligently, and it is downloading the snapshot now.

**Comment by ValarDragon** [comment]
Snapshot finished, and its working on my machine!

**Comment by njmurarka** [comment]
I think the installer might have done its job?

Here is what happens after it ended:

```
Congratulations! You have successfully completed setting up an Osmosis full node!
The cosmovisor service is currently running in the background
To see the status of cosmovisor, run the following command: 'sudo systemctl status cosmovisor'
To see the live logs from cosmovisor, run the following command: 'journalctl -u cosmovisor -f'
ubuntu@ip-172-26-6-126:~$ sudo systemctl status cosmovisor
● cosmovisor.service - Cosmovisor daemon
     Loaded: loaded (/lib/systemd/system/cosmovisor.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-02-03 09:51:09 UTC; 1s ago
    Process: 285528 ExecStart=/home/ubuntu/go/bin/cosmovisor start --home /home/ubuntu/.osmosisd (code=exited, status=1/FAILURE)
   Main PID: 285528 (code=exited, status=1/FAILURE)
ubuntu@ip-172-26-6-126:~$ journalctl -u cosmovisor -f
-- Logs begin at Thu 2023-01-19 09:09:54 UTC. --
Feb 03 09:51:22 ip-172-26-6-126 cosmovisor[285668]:   Monitored File: /home/ubuntu/.osmosisd/data/upgrade-info.json
Feb 03 09:51:22 ip-172-26-6-126 cosmovisor[285668]:  module=cosmovisor
Feb 03 09:51:22 ip-172-26-6-126 cosmovisor[285668]: 9:51AM INF running app args=["start","--home","/home/ubuntu/.osmosisd"] module=cosmovisor path=/home/ubuntu/.osmosisd/cosmovisor/genesis/bin/osmosisd
Feb 03 09:51:22 ip-172-26-6-126 cosmovisor[285668]: 9:51AM ERR failed to read error="lstat /home/ubuntu/.osmosisd/cosmovisor/current/upgrade-info.json: no such file or directory" filename=/home/ubuntu/.osmosisd/cosmovisor/current/upgrade-info.json module=cosmovisor
Feb 03 09:51:22 ip-172-26-6-126 cosmovisor[285682]: 9:51AM INF starting ABCI with Tendermint
Feb 03 09:51:22 ip-172-26-6-126 cosmovisor[285682]: Error: failed to initialize database: resource temporarily unavailable
Feb 03 09:51:23 ip-172-26-6-126 cosmovisor[285668]: 9:51AM INF pre-upgrade command does not exist. continuing the upgrade. module=cosmovisor
Feb 03 09:51:23 ip-172-26-6-126 cosmovisor[285668]: 9:51AM ERR  error="binary not present, downloading disabled: cannot stat dir /home/ubuntu/.osmosisd/cosmovisor/upgrades/v14/bin/osmosisd: stat /home/ubuntu/.osmosisd/cosmovisor/upgrades/v14/bin/osmosisd: no such file or directory" module=cosmovisor
Feb 03 09:51:23 ip-172-26-6-126 systemd[1]: cosmovisor.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 09:51:23 ip-172-26-6-126 systemd[1]: cosmovisor.service: Failed with result 'exit-code'.
Feb 03 09:51:26 ip-172-26-6-126 systemd[1]: cosmovisor.service: Scheduled restart job, restart counter is at 11.
Feb 03 09:51:26 ip-172-26-6-126 systemd[1]: Stopped Cosmovisor daemon.
Feb 03 09:51:26 ip-172-26-6-126 systemd[1]: Started Cosmovisor daemon.
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]: 9:51AM INF Configuration is valid:
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]: Configurable Values:
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   DAEMON_HOME: /home/ubuntu/.osmosisd
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   DAEMON_NAME: osmosisd
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   DAEMON_ALLOW_DOWNLOAD_BINARIES: false
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   DAEMON_RESTART_AFTER_UPGRADE: true
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   DAEMON_POLL_INTERVAL: 300ms
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   UNSAFE_SKIP_BACKUP: true
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   DAEMON_PREUPGRADE_MAX_RETRIES: 0
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]: Derived Values:
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:         Root Dir: /home/ubuntu/.osmosisd/cosmovisor
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:      Upgrade Dir: /home/ubuntu/.osmosisd/cosmovisor/upgrades
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:      Genesis Bin: /home/ubuntu/.osmosisd/cosmovisor/genesis/bin/osmosisd
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:   Monitored File: /home/ubuntu/.osmosisd/data/upgrade-info.json
Feb 03 09:51:26 ip-172-26-6-126 cosmovisor[285704]:  module=cosmovisor
